---
-
 name: Trabalhando com Handlers
 hosts: web
 remote_user: ansible-core
 become: yes

 tasks:
   - name: Testando handlers do Apache
     yum: name={{ item }} state=installed
     with_items:
       - httpd
       - memcached
     notify: Restart Apache

   - template: src=templates/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
     notify: Restart Apache

 handlers:
   - name: Restart Apache
     service: name=httpd state=restarted
